apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - merge:
      # Merge where this key is the same, will lead to the second generator overwriting the first
      mergeKeys:
        - key
      generators:
      # First generator fetches all directories
      - matrix:
          generators:
            # git generator, fetches all directories
            - git:
                repoURL: https://github.com/kartverket/argocd-apps-repo-demo.git
                revision: HEAD
                directories:
                  - path: "env/*/*"
            ## Defaults when no configfile is present
            - list:
                elements:
                - key: "{{ .path.basenameNormalized }}"
                  autoSync: true
                  prune: true
                  allowEmpty: false
                  selfHeal: true
      # Second generator fetches all directories with config.json
      # The merge generator merges the values of the configfile into the above generator
      - matrix:
          generators:
            # git generator, fetches overrides from config.json where present
            - git:
                repoURL: https://github.com/kartverket/argocd-apps-repo-demo.git
                revision: HEAD
                files:
                  - path: "env/**/config.json"
            ## Defaults when no configfile is present
            - list:
                elements:
                - key: "{{ .path.basenameNormalized }}"
                  autoSync: true
                  prune: true
                  allowEmpty: false
                  selfHeal: true
  template:
    metadata:
      name: '{{.path.basenameNormalized}}'
    spec:
      destination:
        name: in-cluster
        namespace: '{{.path.basenameNormalized}}'
      ignoreDifferences:
        - group: external-secrets.io
          jqPathExpressions:
            - '.spec.data[].remoteRef.conversionStrategy'
            - '.spec.data[].remoteRef.decodingStrategy'
          kind: ExternalSecret
      project: default
      source:
        path: '{{.path.path}}'
        repoURL: 'https://github.com/kartverket/argocd-apps-repo-demo.git'
        targetRevision: HEAD
        directory:
          exclude: config.json
      syncPolicy:
        managedNamespaceMetadata:
          annotations: {}
          labels:
            app.kubernetes.io/managed-by: argocd
            istio.io/rev: asm-stable
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PrunePropagationPolicy=background

  # Apply configfile patches
  templatePatch: |
    {{- if .autoSync }}
    spec:
      syncPolicy:
        automated:
          allowEmpty: {{ .allowEmpty }}
          prune: {{ .prune }}
          selfHeal: {{ .selfHeal }}
    {{- end }}
